# Generated by Django 2.0.5 on 2018-05-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200), max_length=100),
        ),
    ]
